/**
 * Compound Savings PDF Report Generator
 */

import type { CompoundSavingsInput, CompoundSavingsResult } from './compoundSavingsCalculator';
import {
  initPdfMake,
  buildHeaderContent,
  buildBackground,
  buildFooter,
  fmtCurrency,
  fmtNum,
  lbl,
  rtl,
  formatDateArabic,
  formatDate,
  thinGridLayout,
  amortGridLayout,
  NAVY,
  WHITE,
  LIGHT_GRAY,
  ALT_ROW_GREEN,
  ALT_ROW_BLUE,
} from './pdfReportBase';

// ===== LABELS =====

interface Labels {
  title: string; subtitle: string;
  inputParameters: string; resultsSummary: string;
  yearsToInvest: string; initialInvestment: string; annualInterestRate: string;
  depositAmount: string; depositFrequency: string; extraAnnualDeposit: string;
  futureValue: string; totalInvested: string; interestEarned: string;
  growthSchedule: string;
  year: string; rate: string; interest: string; scheduledDeposits: string;
  extraDeposit: string; balance: string; cumulativeContribution: string; cumulativeInterest: string;
  generatedBy: string; generatedOn: string; page: string; of: string; years: string;
  monthly: string; quarterly: string; annually: string;
}

const EN: Labels = {
  title: 'Compound Savings Report', subtitle: 'Savings Growth Projection',
  inputParameters: 'Savings Plan Inputs', resultsSummary: 'Summary of Results',
  yearsToInvest: 'Years to Invest', initialInvestment: 'Initial Investment',
  annualInterestRate: 'Expected Annual Interest Rate',
  depositAmount: 'Deposit Amount', depositFrequency: 'Deposit Frequency',
  extraAnnualDeposit: 'Additional Annual Investment',
  futureValue: 'Estimated Future Value', totalInvested: 'Total Invested',
  interestEarned: 'Interest Earned',
  growthSchedule: 'Savings Growth Schedule',
  year: 'Year', rate: 'Rate', interest: 'Interest', scheduledDeposits: 'Scheduled Deposits',
  extraDeposit: 'Extra Annual Deposits', balance: 'Balance',
  cumulativeContribution: 'Cumulative Contribution', cumulativeInterest: 'Cumulative Interest',
  generatedBy: 'Generated by Rasmalak AI', generatedOn: 'Generated on',
  page: 'Page', of: 'of', years: 'years',
  monthly: 'Monthly', quarterly: 'Quarterly', annually: 'Annually',
};

const AR: Labels = {
  title: 'تقرير الادخار بالفائدة المركبة', subtitle: 'توقع نمو الادخار',
  inputParameters: 'مدخلات خطة التوفير', resultsSummary: 'ملخص النتائج',
  yearsToInvest: 'سنوات الاستثمار', initialInvestment: 'الاستثمار الأولي',
  annualInterestRate: 'نسبة الفائدة السنوية المتوقعة',
  depositAmount: 'مبلغ الإيداع', depositFrequency: 'تكرار الإيداع',
  extraAnnualDeposit: 'استثمار سنوي إضافي',
  futureValue: 'القيمة المستقبلية المقدرة', totalInvested: 'المبلغ المستثمر',
  interestEarned: 'الفائدة المقدرة',
  growthSchedule: 'جدول نمو الادخار',
  year: 'السنة', rate: 'النسبة', interest: 'قيمة الفائدة', scheduledDeposits: 'الإيداع',
  extraDeposit: 'إيداع إضافي', balance: 'الرصيد',
  cumulativeContribution: 'مجموع الإيداع', cumulativeInterest: 'مجموع الفائدة',
  generatedBy: 'تم إنشاؤه بواسطة رسملك', generatedOn: 'تاريخ الإنشاء',
  page: 'صفحة', of: 'من', years: 'سنة',
  monthly: 'شهري', quarterly: 'ربع سنوي', annually: 'سنوي',
};

function freqLabel(freq: string, labels: Labels): string {
  switch (freq) {
    case 'monthly': return labels.monthly;
    case 'quarterly': return labels.quarterly;
    case 'annually': return labels.annually;
    default: return freq;
  }
}

// ===== MAIN =====

export async function generateCompoundSavingsPDF(
  input: CompoundSavingsInput,
  result: CompoundSavingsResult,
  locale: string = 'en',
  currencySymbol: string = '$',
): Promise<void> {
  const isArabic = locale === 'ar';
  const labels = isArabic ? AR : EN;
  const align = isArabic ? 'right' as const : 'left' as const;
  const fontFamily = isArabic ? 'Amiri' : 'Roboto';

  const pdfMake = await initPdfMake(isArabic);

  const now = new Date();
  const generatedDateStr = isArabic
    ? rtl(`${labels.generatedOn}: ${formatDateArabic(now)}`)
    : `${labels.generatedOn}: ${formatDate(now)}`;

  const fmtPct = (v: number) => isArabic
    ? rtl(`${fmtNum(v * 100, isArabic)}%`)
    : `${(v * 100).toFixed(2)}%`;

  // Input table
  const inputRows = [
    [lbl(labels.yearsToInvest, isArabic), isArabic ? rtl(`${fmtNum(input.yearsToInvest, isArabic, 0)} ${labels.years}`) : `${input.yearsToInvest} ${labels.years}`],
    [lbl(labels.initialInvestment, isArabic), fmtCurrency(input.initialInvestment, currencySymbol, isArabic)],
    [lbl(labels.annualInterestRate, isArabic), fmtPct(input.annualInterestRate)],
    [lbl(labels.depositAmount, isArabic), fmtCurrency(input.depositAmount, currencySymbol, isArabic)],
    [lbl(labels.depositFrequency, isArabic), lbl(freqLabel(input.depositFrequency, labels), isArabic)],
    [lbl(labels.extraAnnualDeposit, isArabic), fmtCurrency(input.extraAnnualDeposit, currencySymbol, isArabic)],
  ];

  // Summary table
  const summaryRows = [
    [lbl(labels.futureValue, isArabic), fmtCurrency(result.summary.futureValue, currencySymbol, isArabic)],
    [lbl(labels.totalInvested, isArabic), fmtCurrency(result.summary.totalInvested, currencySymbol, isArabic)],
    [lbl(labels.interestEarned, isArabic), fmtCurrency(result.summary.interestEarned, currencySymbol, isArabic)],
  ];

  const buildTable = (rows: string[][], altColor: string) =>
    rows.map((row, idx) => {
      const fill = idx % 2 === 1 ? altColor : undefined;
      const cells = [
        { text: row[0], bold: true, alignment: align, fillColor: fill },
        { text: row[1], alignment: align, fillColor: fill },
      ];
      return isArabic ? cells.reverse() : cells;
    });

  // Schedule headers
  const schedHeaders = [
    labels.year, labels.rate, labels.interest, labels.scheduledDeposits,
    labels.extraDeposit, labels.balance, labels.cumulativeContribution, labels.cumulativeInterest,
  ].map(h => lbl(h, isArabic));

  const schedHeaderRow = (isArabic ? [...schedHeaders].reverse() : schedHeaders).map(h => ({
    text: h, bold: true, fontSize: 7, color: WHITE, fillColor: NAVY, alignment: 'center' as const,
  }));

  const schedBody = result.schedule.map((row, idx) => {
    const fillColor = idx % 2 === 1 ? LIGHT_GRAY : undefined;
    const cells = [
      { text: fmtNum(row.year, isArabic, 0), alignment: 'center' as const, fillColor },
      { text: fmtPct(row.rate), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.interest, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.scheduledDeposits, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.extraDeposit, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.balance, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.cumulativeContribution, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.cumulativeInterest, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
    ];
    return isArabic ? cells.reverse() : cells;
  });

  const leftTable = {
    width: '50%',
    stack: [
      { text: lbl(isArabic ? labels.resultsSummary : labels.inputParameters, isArabic), fontSize: 11, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      { table: { headerRows: 0, widths: ['50%', '50%'], body: isArabic ? buildTable(summaryRows, ALT_ROW_BLUE) : buildTable(inputRows, ALT_ROW_GREEN) }, layout: thinGridLayout },
    ],
  };

  const rightTable = {
    width: '50%',
    stack: [
      { text: lbl(isArabic ? labels.inputParameters : labels.resultsSummary, isArabic), fontSize: 11, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      { table: { headerRows: 0, widths: ['50%', '50%'], body: isArabic ? buildTable(inputRows, ALT_ROW_GREEN) : buildTable(summaryRows, ALT_ROW_BLUE) }, layout: thinGridLayout },
    ],
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const docDefinition: any = {
    pageOrientation: 'landscape',
    pageSize: 'A4',
    pageMargins: [15, 15, 15, 25],
    defaultStyle: { font: fontFamily, fontSize: 8 },
    background: buildBackground,
    content: [
      buildHeaderContent(labels.title, labels.subtitle, generatedDateStr, isArabic, fontFamily),
      { columns: [leftTable, { width: 15, text: '' }, rightTable], marginBottom: 15 },
      { text: lbl(labels.growthSchedule, isArabic), fontSize: 12, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      { table: { headerRows: 1, widths: Array(8).fill('*'), body: [schedHeaderRow, ...schedBody] }, layout: amortGridLayout, fontSize: 6.5 },
    ],
    footer: buildFooter(labels.generatedBy, labels.page, labels.of, isArabic, fontFamily),
  };

  const fileName = isArabic ? 'تقرير_الادخار_المركب.pdf' : 'Compound_Savings_Report.pdf';
  pdfMake.createPdf(docDefinition).download(fileName);
}
