/**
 * Credit Card Payment PDF Report Generator
 */

import type { CreditCardInput, CreditCardResult } from './creditCardCalculator';
import {
  initPdfMake,
  buildHeaderContent,
  buildBackground,
  buildFooter,
  fmtCurrency,
  fmtNum,
  lbl,
  rtl,
  toArabicNumerals,
  formatDateArabic,
  formatDate,
  thinGridLayout,
  amortGridLayout,
  NAVY,
  WHITE,
  LIGHT_GRAY,
  ALT_ROW_GREEN,
  ALT_ROW_BLUE,
} from './pdfReportBase';

// ===== LABELS =====

interface Labels {
  title: string; subtitle: string; inputParameters: string; resultsSummary: string;
  currentBalance: string; interestRate: string; minPaymentPercent: string;
  plusInterest: string; minPaymentFloor: string; fixedPayment: string;
  introMonths: string; firstPayment: string; maxPayment: string;
  monthsToPayOff: string; yearsToPayOff: string; totalInterest: string; totalPaid: string;
  paymentSchedule: string;
  pmtNo: string; rate: string; payment: string; extraPayment: string;
  totalPayment: string; interestPaid: string; principalPaid: string; balance: string;
  generatedBy: string; generatedOn: string; page: string; of: string;
  yes: string; no: string; months: string;
}

const EN: Labels = {
  title: 'Credit Card Payment Schedule', subtitle: 'Credit Card Payoff Report',
  inputParameters: 'Card Details', resultsSummary: 'Payoff Summary',
  currentBalance: 'Current Balance', interestRate: 'Interest Rate',
  minPaymentPercent: 'Min Payment % of Balance', plusInterest: 'Plus Interest?',
  minPaymentFloor: 'Min Payment Floor', fixedPayment: 'Fixed Monthly Payment',
  introMonths: '0% Intro Period',
  firstPayment: 'First Payment', maxPayment: 'Max Payment',
  monthsToPayOff: 'Months to Pay Off', yearsToPayOff: 'Years to Pay Off',
  totalInterest: 'Total Interest Paid', totalPaid: 'Total Amount Paid',
  paymentSchedule: 'Payment Schedule',
  pmtNo: 'No.', rate: 'Rate', payment: 'Payment', extraPayment: 'Extra Payment',
  totalPayment: 'Total Payment', interestPaid: 'Interest Paid',
  principalPaid: 'Principal Paid', balance: 'Balance',
  generatedBy: 'Generated by Rasmalak AI', generatedOn: 'Generated on',
  page: 'Page', of: 'of', yes: 'Yes', no: 'No', months: 'months',
};

const AR: Labels = {
  title: 'جدول سداد بطاقة الائتمان', subtitle: 'تقرير سداد بطاقة الائتمان',
  inputParameters: 'بيانات البطاقة', resultsSummary: 'ملخص السداد',
  currentBalance: 'الرصيد الحالي', interestRate: 'نسبة الفائدة',
  minPaymentPercent: 'نسبة الحد الأدنى من الرصيد', plusInterest: 'بالإضافة للفائدة؟',
  minPaymentFloor: 'الحد الأدنى للدفعة', fixedPayment: 'دفعة شهرية ثابتة',
  introMonths: 'فترة بدون فائدة',
  firstPayment: 'الدفعة الأولى', maxPayment: 'أعلى دفعة',
  monthsToPayOff: 'أشهر السداد', yearsToPayOff: 'سنوات السداد',
  totalInterest: 'إجمالي الفائدة المدفوعة', totalPaid: 'إجمالي المبلغ المدفوع',
  paymentSchedule: 'جدول الدفعات',
  pmtNo: 'رقم', rate: 'النسبة', payment: 'الدفعة', extraPayment: 'دفعة إضافية',
  totalPayment: 'إجمالي الدفعة', interestPaid: 'الفائدة المدفوعة',
  principalPaid: 'المبلغ الأصلي', balance: 'الرصيد',
  generatedBy: 'تم إنشاؤه بواسطة رسملك', generatedOn: 'تاريخ الإنشاء',
  page: 'صفحة', of: 'من', yes: 'نعم', no: 'لا', months: 'شهر',
};

// ===== MAIN =====

export async function generateCreditCardPDF(
  input: CreditCardInput,
  result: CreditCardResult,
  locale: string = 'en',
  currencySymbol: string = '$',
): Promise<void> {
  const isArabic = locale === 'ar';
  const labels = isArabic ? AR : EN;
  const align = isArabic ? 'right' as const : 'left' as const;
  const fontFamily = isArabic ? 'Amiri' : 'Roboto';

  const pdfMake = await initPdfMake(isArabic);

  const now = new Date();
  const generatedDateStr = isArabic
    ? rtl(`${labels.generatedOn}: ${formatDateArabic(now)}`)
    : `${labels.generatedOn}: ${formatDate(now)}`;

  // Input table
  const inputRows = [
    [lbl(labels.currentBalance, isArabic), fmtCurrency(input.currentBalance, currencySymbol, isArabic)],
    [lbl(labels.interestRate, isArabic), isArabic ? rtl(`${fmtNum(input.annualInterestRate, isArabic)}%`) : `${input.annualInterestRate}%`],
    [lbl(labels.minPaymentPercent, isArabic), isArabic ? rtl(`${fmtNum(input.minPaymentPercent, isArabic)}%`) : `${input.minPaymentPercent}%`],
    [lbl(labels.plusInterest, isArabic), lbl(input.minPaymentPlusInterest ? labels.yes : labels.no, isArabic)],
    [lbl(labels.minPaymentFloor, isArabic), fmtCurrency(input.minPaymentFloor, currencySymbol, isArabic)],
    [lbl(labels.fixedPayment, isArabic), input.fixedMonthlyPayment > 0 ? fmtCurrency(input.fixedMonthlyPayment, currencySymbol, isArabic) : '-'],
    [lbl(labels.introMonths, isArabic), isArabic ? rtl(`${toArabicNumerals(String(input.introMonths))} ${labels.months}`) : `${input.introMonths} ${labels.months}`],
  ];

  // Summary table
  const summaryRows = [
    [lbl(labels.firstPayment, isArabic), fmtCurrency(result.summary.firstPayment, currencySymbol, isArabic)],
    [lbl(labels.maxPayment, isArabic), fmtCurrency(result.summary.maxPayment, currencySymbol, isArabic)],
    [lbl(labels.monthsToPayOff, isArabic), fmtNum(result.summary.monthsToPayOff, isArabic, 0)],
    [lbl(labels.yearsToPayOff, isArabic), fmtNum(result.summary.yearsToPayOff, isArabic)],
    [lbl(labels.totalInterest, isArabic), fmtCurrency(result.summary.totalInterestPaid, currencySymbol, isArabic)],
    [lbl(labels.totalPaid, isArabic), fmtCurrency(result.summary.totalAmountPaid, currencySymbol, isArabic)],
  ];

  const buildTable = (rows: string[][], altColor: string) =>
    rows.map((row, idx) => {
      const fill = idx % 2 === 1 ? altColor : undefined;
      const cells = [
        { text: row[0], bold: true, alignment: align, fillColor: fill },
        { text: row[1], alignment: align, fillColor: fill },
      ];
      return isArabic ? cells.reverse() : cells;
    });

  // Schedule headers
  const schedHeaders = [
    labels.pmtNo, labels.rate, labels.payment, labels.extraPayment,
    labels.totalPayment, labels.interestPaid, labels.principalPaid, labels.balance,
  ].map(h => lbl(h, isArabic));

  const schedHeaderRow = (isArabic ? [...schedHeaders].reverse() : schedHeaders).map(h => ({
    text: h, bold: true, fontSize: 7, color: WHITE, fillColor: NAVY, alignment: 'center' as const,
  }));

  const schedBody = result.schedule.map((row, idx) => {
    const fillColor = idx % 2 === 1 ? LIGHT_GRAY : undefined;
    const cells = [
      { text: fmtNum(row.paymentNumber, isArabic, 0), alignment: 'center' as const, fillColor },
      { text: isArabic ? rtl(`${fmtNum(row.rate, isArabic)}%`) : `${row.rate}%`, alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.payment, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.extraPayment, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.totalPayment, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.interestPaid, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.principalPaid, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.balance, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
    ];
    return isArabic ? cells.reverse() : cells;
  });

  const leftTable = {
    width: '50%',
    stack: [
      { text: lbl(isArabic ? labels.resultsSummary : labels.inputParameters, isArabic), fontSize: 11, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      { table: { headerRows: 0, widths: ['50%', '50%'], body: isArabic ? buildTable(summaryRows, ALT_ROW_BLUE) : buildTable(inputRows, ALT_ROW_GREEN) }, layout: thinGridLayout },
    ],
  };

  const rightTable = {
    width: '50%',
    stack: [
      { text: lbl(isArabic ? labels.inputParameters : labels.resultsSummary, isArabic), fontSize: 11, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      { table: { headerRows: 0, widths: ['50%', '50%'], body: isArabic ? buildTable(inputRows, ALT_ROW_GREEN) : buildTable(summaryRows, ALT_ROW_BLUE) }, layout: thinGridLayout },
    ],
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const docDefinition: any = {
    pageOrientation: 'landscape',
    pageSize: 'A4',
    pageMargins: [15, 15, 15, 25],
    defaultStyle: { font: fontFamily, fontSize: 8 },
    background: buildBackground,
    content: [
      buildHeaderContent(labels.title, labels.subtitle, generatedDateStr, isArabic, fontFamily),
      { columns: [leftTable, { width: 15, text: '' }, rightTable], marginBottom: 15 },
      { text: lbl(labels.paymentSchedule, isArabic), fontSize: 12, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      { table: { headerRows: 1, widths: Array(8).fill('*'), body: [schedHeaderRow, ...schedBody] }, layout: amortGridLayout, fontSize: 6.5 },
    ],
    footer: buildFooter(labels.generatedBy, labels.page, labels.of, isArabic, fontFamily),
  };

  const fileName = isArabic ? 'تقرير_سداد_بطاقة_الائتمان.pdf' : 'Credit_Card_Payment_Report.pdf';
  pdfMake.createPdf(docDefinition).download(fileName);
}

