/**
 * Home Affordability PDF Report Generator
 *
 * No amortization schedule – just a summary of input + results.
 */

import type { HomeAffordabilityInput, HomeAffordabilityResult } from './homeAffordabilityCalculator';
import {
  initPdfMake,
  buildHeaderContent,
  buildBackground,
  buildFooter,
  fmtCurrency,
  fmtNum,
  lbl,
  rtl,
  formatDateArabic,
  formatDate,
  thinGridLayout,
  NAVY,
  ALT_ROW_GREEN,
  ALT_ROW_BLUE,
} from './pdfReportBase';

// ===== LABELS =====

interface Labels {
  title: string; subtitle: string;
  incomeSection: string; debtsSection: string; housingSection: string;
  fundsSection: string; financingSection: string; resultsSection: string;
  grossAnnualIncome: string; maxHousingPercent: string;
  carLoans: string; creditCards: string; studentLoans: string;
  childSupport: string; otherMortgages: string; otherLoans: string; currentDebts: string;
  maxDTI: string;
  propertyTax: string; insurance: string; pmi: string; hoa: string; otherExpenses: string;
  availableFunds: string; fixedClosing: string; variableClosing: string; minDownPayment: string;
  mortgageTerm: string; interestRate: string;
  m1Income: string; m2DTI: string; maxMonthlyPayment: string;
  m3Expenses: string; m4Funds: string; maxPIPayment: string;
  loanAmount: string; downPayment: string; closingCosts: string; maxHomePrice: string;
  generatedBy: string; generatedOn: string; page: string; of: string; years: string;
}

const EN: Labels = {
  title: 'Home Affordability Analysis', subtitle: 'How Much Home Can You Afford?',
  incomeSection: 'Income', debtsSection: 'Monthly Debts', housingSection: 'Housing Expenses',
  fundsSection: 'Available Funds', financingSection: 'Financing', resultsSection: 'Affordability Results',
  grossAnnualIncome: 'Gross Annual Income', maxHousingPercent: 'Max Housing Expense %',
  carLoans: 'Car Loans', creditCards: 'Credit Card Minimums', studentLoans: 'Student Loans',
  childSupport: 'Child Support & Other', otherMortgages: 'Other Mortgages', otherLoans: 'Other Loans',
  currentDebts: 'Current Monthly Debts', maxDTI: 'Max Debt-to-Income Ratio',
  propertyTax: 'Property Tax (Monthly)', insurance: 'Home Insurance (Monthly)',
  pmi: 'PMI', hoa: 'HOA Fees', otherExpenses: 'Other Expenses',
  availableFunds: 'Available Funds', fixedClosing: 'Fixed Closing Costs',
  variableClosing: 'Variable Closing Costs %', minDownPayment: 'Min Down Payment %',
  mortgageTerm: 'Mortgage Term', interestRate: 'Interest Rate',
  m1Income: 'M1 Max Payment (Income)', m2DTI: 'M2 Max Payment (DTI)',
  maxMonthlyPayment: 'Max Monthly Payment',
  m3Expenses: 'M3 Max PI (Expenses)', m4Funds: 'M4 Max PI (Funds)',
  maxPIPayment: 'Max PI Payment',
  loanAmount: 'Loan Amount', downPayment: 'Down Payment', closingCosts: 'Closing Costs',
  maxHomePrice: 'Maximum Home Price',
  generatedBy: 'Generated by Rasmalak AI', generatedOn: 'Generated on',
  page: 'Page', of: 'of', years: 'years',
};

const AR: Labels = {
  title: 'تحليل القدرة على شراء المنزل', subtitle: 'ما هو سعر المنزل الذي يمكنك تحمله؟',
  incomeSection: 'الدخل', debtsSection: 'الديون الشهرية', housingSection: 'مصاريف السكن',
  fundsSection: 'الأموال المتاحة', financingSection: 'التمويل', resultsSection: 'نتائج القدرة الشرائية',
  grossAnnualIncome: 'إجمالي الدخل السنوي', maxHousingPercent: 'الحد الأقصى لنسبة مصاريف السكن',
  carLoans: 'قروض السيارات', creditCards: 'الحد الأدنى لبطاقات الائتمان',
  studentLoans: 'قروض التعليم', childSupport: 'النفقة والتزامات أخرى',
  otherMortgages: 'رهون عقارية أخرى', otherLoans: 'قروض أخرى',
  currentDebts: 'إجمالي الديون الشهرية', maxDTI: 'الحد الأقصى لنسبة الدين للدخل',
  propertyTax: 'ضريبة العقار (شهري)', insurance: 'تأمين المنزل (شهري)',
  pmi: 'تأمين الرهن العقاري', hoa: 'رسوم جمعية الملاك', otherExpenses: 'مصاريف أخرى',
  availableFunds: 'الأموال المتاحة', fixedClosing: 'تكاليف الإغلاق الثابتة',
  variableClosing: 'نسبة تكاليف الإغلاق المتغيرة', minDownPayment: 'الحد الأدنى للدفعة المقدمة',
  mortgageTerm: 'مدة القرض العقاري', interestRate: 'نسبة الفائدة',
  m1Income: 'الحد الأقصى (الدخل)', m2DTI: 'الحد الأقصى (نسبة الدين)',
  maxMonthlyPayment: 'أقصى دفعة شهرية',
  m3Expenses: 'الحد الأقصى PI (المصاريف)', m4Funds: 'الحد الأقصى PI (الأموال)',
  maxPIPayment: 'أقصى دفعة PI',
  loanAmount: 'مبلغ القرض', downPayment: 'الدفعة المقدمة', closingCosts: 'تكاليف الإغلاق',
  maxHomePrice: 'أقصى سعر للمنزل',
  generatedBy: 'تم إنشاؤه بواسطة رسملك', generatedOn: 'تاريخ الإنشاء',
  page: 'صفحة', of: 'من', years: 'سنة',
};

// ===== MAIN =====

export async function generateHomeAffordabilityPDF(
  input: HomeAffordabilityInput,
  result: HomeAffordabilityResult,
  locale: string = 'en',
  currencySymbol: string = '$',
): Promise<void> {
  const isArabic = locale === 'ar';
  const labels = isArabic ? AR : EN;
  const align = isArabic ? 'right' as const : 'left' as const;
  const fontFamily = isArabic ? 'Amiri' : 'Roboto';

  const pdfMake = await initPdfMake(isArabic);

  const now = new Date();
  const generatedDateStr = isArabic
    ? rtl(`${labels.generatedOn}: ${formatDateArabic(now)}`)
    : `${labels.generatedOn}: ${formatDate(now)}`;

  // Helper
  const pctStr = (v: number) => isArabic ? rtl(`${fmtNum(v, isArabic)}%`) : `${v}%`;

  // Build rows
  const incomeRows = [
    [lbl(labels.grossAnnualIncome, isArabic), fmtCurrency(input.grossAnnualIncome, currencySymbol, isArabic)],
    [lbl(labels.maxHousingPercent, isArabic), pctStr(input.maxHousingExpensePercent)],
    [lbl(labels.m1Income, isArabic), fmtCurrency(result.m1MaxPaymentIncome, currencySymbol, isArabic)],
  ];

  const debtRows = [
    [lbl(labels.carLoans, isArabic), fmtCurrency(input.carLoans, currencySymbol, isArabic)],
    [lbl(labels.creditCards, isArabic), fmtCurrency(input.creditCardMinimums, currencySymbol, isArabic)],
    [lbl(labels.studentLoans, isArabic), fmtCurrency(input.studentLoans, currencySymbol, isArabic)],
    [lbl(labels.childSupport, isArabic), fmtCurrency(input.childSupportOther, currencySymbol, isArabic)],
    [lbl(labels.otherMortgages, isArabic), fmtCurrency(input.otherMortgages, currencySymbol, isArabic)],
    [lbl(labels.otherLoans, isArabic), fmtCurrency(input.otherLoans, currencySymbol, isArabic)],
    [lbl(labels.currentDebts, isArabic), fmtCurrency(result.currentMonthlyDebts, currencySymbol, isArabic)],
    [lbl(labels.maxDTI, isArabic), pctStr(input.maxDTIRatio)],
    [lbl(labels.m2DTI, isArabic), fmtCurrency(result.m2MaxPaymentDTI, currencySymbol, isArabic)],
  ];

  const housingRows = [
    [lbl(labels.propertyTax, isArabic), fmtCurrency(input.propertyTaxMonthly, currencySymbol, isArabic)],
    [lbl(labels.insurance, isArabic), fmtCurrency(input.homeInsuranceMonthly, currencySymbol, isArabic)],
    [lbl(labels.pmi, isArabic), fmtCurrency(input.pmiMonthly, currencySymbol, isArabic)],
    [lbl(labels.hoa, isArabic), fmtCurrency(input.hoaFees, currencySymbol, isArabic)],
    [lbl(labels.otherExpenses, isArabic), fmtCurrency(input.otherHousingExpenses, currencySymbol, isArabic)],
  ];

  const fundsRows = [
    [lbl(labels.availableFunds, isArabic), fmtCurrency(input.availableFunds, currencySymbol, isArabic)],
    [lbl(labels.fixedClosing, isArabic), fmtCurrency(input.fixedClosingCosts, currencySymbol, isArabic)],
    [lbl(labels.variableClosing, isArabic), pctStr(input.variableClosingCostsPercent)],
    [lbl(labels.minDownPayment, isArabic), pctStr(input.minDownPaymentPercent)],
  ];

  const financingRows = [
    [lbl(labels.mortgageTerm, isArabic), isArabic ? rtl(`${fmtNum(input.mortgageTermYears, isArabic, 0)} ${labels.years}`) : `${input.mortgageTermYears} ${labels.years}`],
    [lbl(labels.interestRate, isArabic), pctStr(input.annualInterestRate)],
  ];

  const resultsRows = [
    [lbl(labels.maxMonthlyPayment, isArabic), fmtCurrency(result.maxMonthlyPayment, currencySymbol, isArabic)],
    [lbl(labels.m3Expenses, isArabic), fmtCurrency(result.m3MaxPIExpenses, currencySymbol, isArabic)],
    [lbl(labels.m4Funds, isArabic), fmtCurrency(result.m4MaxPIFunds, currencySymbol, isArabic)],
    [lbl(labels.maxPIPayment, isArabic), fmtCurrency(result.maxPIPayment, currencySymbol, isArabic)],
    [lbl(labels.loanAmount, isArabic), fmtCurrency(result.loanAmount, currencySymbol, isArabic)],
    [lbl(labels.downPayment, isArabic), `${fmtCurrency(result.downPaymentAmount, currencySymbol, isArabic)} (${pctStr(result.downPaymentPercent)})`],
    [lbl(labels.closingCosts, isArabic), `${fmtCurrency(result.estimatedClosingCosts, currencySymbol, isArabic)} (${pctStr(result.closingCostsPercent)})`],
    [lbl(labels.maxHomePrice, isArabic), fmtCurrency(result.maxHomePrice, currencySymbol, isArabic)],
  ];

  const buildTableBody = (rows: string[][], altColor: string) =>
    rows.map((row, idx) => {
      const fill = idx % 2 === 1 ? altColor : undefined;
      const cells = [
        { text: row[0], bold: true, alignment: align, fillColor: fill },
        { text: row[1], alignment: align, fillColor: fill },
      ];
      return isArabic ? cells.reverse() : cells;
    });

  const makeSection = (title: string, rows: string[][], altColor: string) => ([
    { text: lbl(title, isArabic), fontSize: 10, bold: true, color: NAVY, alignment: align, marginBottom: 3, marginTop: 8 },
    { table: { headerRows: 0, widths: ['50%', '50%'], body: buildTableBody(rows, altColor) }, layout: thinGridLayout },
  ]);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const content: any[] = [
    buildHeaderContent(labels.title, labels.subtitle, generatedDateStr, isArabic, fontFamily),
    ...makeSection(labels.incomeSection, incomeRows, ALT_ROW_GREEN),
    ...makeSection(labels.debtsSection, debtRows, ALT_ROW_GREEN),
    ...makeSection(labels.housingSection, housingRows, ALT_ROW_GREEN),
    ...makeSection(labels.fundsSection, fundsRows, ALT_ROW_GREEN),
    ...makeSection(labels.financingSection, financingRows, ALT_ROW_GREEN),
    ...makeSection(labels.resultsSection, resultsRows, ALT_ROW_BLUE),
  ];

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const docDefinition: any = {
    pageOrientation: 'portrait',
    pageSize: 'A4',
    pageMargins: [30, 15, 30, 25],
    defaultStyle: { font: fontFamily, fontSize: 9 },
    background: (currentPage: number) => {
      if (currentPage === 1) {
        return [
          { canvas: [{ type: 'rect', x: 0, y: 0, w: 595, h: 32, color: NAVY }] },
          { canvas: [{ type: 'rect', x: 0, y: 32, w: 595, h: 2, color: '#10B981' }] },
        ];
      }
      return [];
    },
    content,
    footer: buildFooter(labels.generatedBy, labels.page, labels.of, isArabic, fontFamily),
  };

  const fileName = isArabic ? 'تقرير_القدرة_الشرائية.pdf' : 'Home_Affordability_Report.pdf';
  pdfMake.createPdf(docDefinition).download(fileName);
}

