/**
 * Mortgage Payoff PDF Report Generator
 * 
 * Generates a professional PDF report with loan summary and amortization schedule.
 * Supports both English (LTR) and Arabic (RTL) layouts.
 * 
 * Uses pdfmake which internally uses fontkit for proper OpenType text shaping.
 * Arabic text shaping (letter joining, ligatures) is handled automatically.
 */

import type { MortgagePayoffInput, MortgagePayoffResult } from './mortgagePayoffCalculator';
import {
  formatNumber,
  formatNumberArabic,
  formatDate,
  formatDateArabic,
  toArabicNumerals,
  loadArabicFonts,
} from './arabicPdfHelper';

// ===== TYPES =====

interface ReportLabels {
  title: string;
  subtitle: string;
  loanSummary: string;
  amortizationSchedule: string;
  loanAmount: string;
  interestRate: string;
  loanTerm: string;
  paymentsPerYear: string;
  startDate: string;
  extraPayment: string;
  lenderName: string;
  scheduledPayment: string;
  scheduledPayments: string;
  actualPayments: string;
  yearsSaved: string;
  totalEarlyPayments: string;
  totalInterest: string;
  totalPaid: string;
  pmtNo: string;
  paymentDate: string;
  beginningBalance: string;
  scheduledPmt: string;
  extraPmt: string;
  totalPayment: string;
  principal: string;
  interest: string;
  endingBalance: string;
  cumulativeInterest: string;
  generatedBy: string;
  generatedOn: string;
  page: string;
  of: string;
  years: string;
  inputParameters: string;
}

// ===== LABELS =====

const EN_LABELS: ReportLabels = {
  title: 'Mortgage Amortization Schedule',
  subtitle: 'Mortgage Payoff Report',
  loanSummary: 'Loan Summary',
  amortizationSchedule: 'Amortization Schedule',
  loanAmount: 'Loan Amount',
  interestRate: 'Interest Rate',
  loanTerm: 'Loan Term',
  paymentsPerYear: 'Payments Per Year',
  startDate: 'Repayment Start Date',
  extraPayment: 'Extra Monthly Payment',
  lenderName: 'Lender Name',
  scheduledPayment: 'Scheduled Payment',
  scheduledPayments: 'Scheduled Number of Payments',
  actualPayments: 'Actual Number of Payments',
  yearsSaved: 'Years Saved Off Original Loan Term',
  totalEarlyPayments: 'Total Early Payments',
  totalInterest: 'Total Interest',
  totalPaid: 'Total Amount Paid',
  pmtNo: 'PMT No',
  paymentDate: 'Payment Date',
  beginningBalance: 'Beginning Balance',
  scheduledPmt: 'Scheduled Payment',
  extraPmt: 'Extra Payment',
  totalPayment: 'Total Payment',
  principal: 'Principal',
  interest: 'Interest',
  endingBalance: 'Ending Balance',
  cumulativeInterest: 'Cumulative Interest',
  generatedBy: 'Generated by Rasmalak AI',
  generatedOn: 'Generated on',
  page: 'Page',
  of: 'of',
  years: 'years',
  inputParameters: 'Input Parameters',
};

const AR_LABELS: ReportLabels = {
  title: 'جدول سداد القرض السكني',
  subtitle: 'تقرير سداد القرض',
  loanSummary: 'مختصر تفاصيل القرض',
  amortizationSchedule: 'جدول الأقساط',
  loanAmount: 'قيمة القرض',
  interestRate: 'نسبة الفائدة السنوية',
  loanTerm: 'مدة القرض',
  paymentsPerYear: 'عدد الدفعات في السنة',
  startDate: 'تاريخ أول دفعة سداد',
  extraPayment: 'الدفعة الإضافية',
  lenderName: 'اسم البنك المقرض',
  scheduledPayment: 'الدفعة الشهرية',
  scheduledPayments: 'عدد الدفعات الأساسية',
  actualPayments: 'عدد الدفعات الفعلي',
  yearsSaved: 'السنوات المختصرة',
  totalEarlyPayments: 'مجموع الدفعات الإضافية',
  totalInterest: 'الفائدة المدفوعة',
  totalPaid: 'إجمالي المبلغ المدفوع',
  pmtNo: 'رقم الدفعة',
  paymentDate: 'تاريخ الدفعة',
  beginningBalance: 'الرصيد الافتتاحي',
  scheduledPmt: 'الدفعة الشهرية',
  extraPmt: 'الدفعة الإضافية',
  totalPayment: 'مجموع الدفعة',
  principal: 'المبلغ الأصلي',
  interest: 'الفائدة',
  endingBalance: 'الرصيد الختامي',
  cumulativeInterest: 'الفائدة التراكمية',
  generatedBy: 'تم إنشاؤه بواسطة رسملك',
  generatedOn: 'تاريخ الإنشاء',
  page: 'صفحة',
  of: 'من',
  years: 'سنة',
  inputParameters: 'بيانات المدخلات',
};

// ===== COLOR CONSTANTS =====
const NAVY = '#0A192F';
const EMERALD = '#10B981';
const WHITE = '#FFFFFF';
const LIGHT_GRAY = '#F8FAFC';
const ALT_ROW_GREEN = '#F5FAF8';
const ALT_ROW_BLUE = '#F0F4FF';

// ===== HELPERS =====

function fmtCurrency(value: number, currencySymbol: string, isArabic: boolean): string {
  if (isArabic) {
    return `${formatNumberArabic(value)} ${currencySymbol}`;
  }
  return `${currencySymbol} ${formatNumber(value)}`;
}

function fmtNum(value: number, isArabic: boolean, decimals: number = 2): string {
  if (isArabic) return formatNumberArabic(value, decimals);
  return formatNumber(value, decimals);
}

function fmtDate(date: Date, isArabic: boolean): string {
  if (isArabic) return formatDateArabic(date);
  return formatDate(date);
}

// ===== MAIN PDF GENERATOR =====

export async function generateMortgagePayoffPDF(
  input: MortgagePayoffInput,
  result: MortgagePayoffResult,
  locale: string = 'en',
  currencySymbol: string = '$',
): Promise<void> {
  const isArabic = locale === 'ar';
  const labels = isArabic ? AR_LABELS : EN_LABELS;
  const align = isArabic ? 'right' as const : 'left' as const;
  const fontFamily = isArabic ? 'Amiri' : 'Roboto';

  // Dynamically import pdfmake (client-side only)
  const pdfMakeModule = await import('pdfmake/build/pdfmake');
  const pdfMake = pdfMakeModule.default || pdfMakeModule;

  // Always load the default VFS (contains Roboto - needed for brand name in both languages)
  const vfsModule = await import('pdfmake/build/vfs_fonts');
  const vfsFonts = vfsModule.default || vfsModule;
  if (vfsFonts?.pdfMake?.vfs) {
    pdfMake.vfs = { ...pdfMake.vfs, ...vfsFonts.pdfMake.vfs };
  }

  // Set up Arabic fonts if needed
  if (isArabic) {
    const arabicFonts = await loadArabicFonts();
    pdfMake.vfs = pdfMake.vfs || {};
    pdfMake.vfs['Amiri-Regular.ttf'] = arabicFonts.regular;
    pdfMake.vfs['Amiri-Bold.ttf'] = arabicFonts.bold;
  }

  // Register all fonts
  pdfMake.fonts = {
    Roboto: {
      normal: 'Roboto-Regular.ttf',
      bold: 'Roboto-Medium.ttf',
      italics: 'Roboto-Italic.ttf',
      bolditalics: 'Roboto-MediumItalic.ttf',
    },
    ...(isArabic ? {
      Amiri: {
        normal: 'Amiri-Regular.ttf',
        bold: 'Amiri-Bold.ttf',
        italics: 'Amiri-Regular.ttf',
        bolditalics: 'Amiri-Bold.ttf',
      },
    } : {}),
  };

  const yearsLabel = labels.years;
  const now = new Date();
  const generatedDateStr = isArabic
    ? `${labels.generatedOn}: ${formatDateArabic(now)}`
    : `${labels.generatedOn}: ${formatDate(now)}`;

  // ===== BUILD INPUT PARAMETERS TABLE =====
  const inputRows = [
    [labels.loanAmount, fmtCurrency(input.loanAmount, currencySymbol, isArabic)],
    [labels.interestRate, isArabic ? `%${toArabicNumerals(String(input.annualInterestRate))}` : `${input.annualInterestRate}%`],
    [labels.loanTerm, `${fmtNum(input.loanTermYears, isArabic, 0)} ${yearsLabel}`],
    [labels.paymentsPerYear, fmtNum(input.paymentsPerYear, isArabic, 0)],
    [labels.startDate, fmtDate(new Date(input.startDate), isArabic)],
    [labels.extraPayment, fmtCurrency(input.extraPayment, currencySymbol, isArabic)],
    [labels.lenderName, input.lenderName || '-'],
  ];

  // ===== BUILD SUMMARY TABLE =====
  const summaryRows = [
    [labels.scheduledPayment, fmtCurrency(result.summary.scheduledPayment, currencySymbol, isArabic)],
    [labels.scheduledPayments, fmtNum(result.summary.scheduledNumberOfPayments, isArabic, 0)],
    [labels.actualPayments, fmtNum(result.summary.actualNumberOfPayments, isArabic, 0)],
    [labels.yearsSaved, `${fmtNum(result.summary.yearsSaved, isArabic)} ${yearsLabel}`],
    [labels.totalEarlyPayments, fmtCurrency(result.summary.totalEarlyPayments, currencySymbol, isArabic)],
    [labels.totalInterest, fmtCurrency(result.summary.totalInterest, currencySymbol, isArabic)],
    [labels.totalPaid, fmtCurrency(result.summary.totalPaid, currencySymbol, isArabic)],
  ];

  // Build table bodies with alternating row colors
  const inputTableBody = inputRows.map((row, idx) => {
    const fill = idx % 2 === 1 ? ALT_ROW_GREEN : undefined;
    const cells = [
      { text: row[0], bold: true, alignment: align, fillColor: fill },
      { text: row[1], alignment: align, fillColor: fill },
    ];
    return isArabic ? cells.reverse() : cells;
  });

  const summaryTableBody = summaryRows.map((row, idx) => {
    const fill = idx % 2 === 1 ? ALT_ROW_BLUE : undefined;
    const cells = [
      { text: row[0], bold: true, alignment: align, fillColor: fill },
      { text: row[1], alignment: align, fillColor: fill },
    ];
    return isArabic ? cells.reverse() : cells;
  });

  // ===== BUILD AMORTIZATION TABLE =====
  const amortHeaders = [
    labels.pmtNo,
    labels.paymentDate,
    labels.beginningBalance,
    labels.scheduledPmt,
    labels.extraPmt,
    labels.totalPayment,
    labels.principal,
    labels.interest,
    labels.endingBalance,
    labels.cumulativeInterest,
  ];

  const amortHeaderRow = (isArabic ? [...amortHeaders].reverse() : amortHeaders).map(h => ({
    text: h,
    bold: true,
    fontSize: 7,
    color: WHITE,
    fillColor: NAVY,
    alignment: 'center' as const,
  }));

  const amortBody = result.schedule.map((row, idx) => {
    const fillColor = idx % 2 === 1 ? LIGHT_GRAY : undefined;
    const cells = [
      { text: fmtNum(row.paymentNumber, isArabic, 0), alignment: 'center' as const, fillColor },
      { text: fmtDate(row.paymentDate, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.beginningBalance, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.scheduledPayment, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.extraPayment, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.totalPayment, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.principal, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.interest, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.endingBalance, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.cumulativeInterest, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
    ];
    return isArabic ? cells.reverse() : cells;
  });

  // ===== TABLE LAYOUT HELPERS =====
  const thinGridLayout = {
    hLineColor: () => '#E5E7EB',
    vLineColor: () => '#E5E7EB',
    hLineWidth: () => 0.5,
    vLineWidth: () => 0.5,
    paddingLeft: () => 4,
    paddingRight: () => 4,
    paddingTop: () => 3,
    paddingBottom: () => 3,
  };

  const amortGridLayout = {
    hLineColor: () => '#D1D5DB',
    vLineColor: () => '#D1D5DB',
    hLineWidth: () => 0.3,
    vLineWidth: () => 0.3,
    paddingLeft: () => 2,
    paddingRight: () => 2,
    paddingTop: () => 1.5,
    paddingBottom: () => 1.5,
  };

  // ===== BUILD CONTENT =====
  // Header section (part of content, not the repeating header)
  const headerContent = {
    stack: [
      // Navy background + emerald line are drawn via background function
      {
        columns: [
          {
            stack: [
              { text: labels.title, fontSize: 16, bold: true, color: WHITE, alignment: isArabic ? 'right' : 'left' },
              { text: labels.subtitle, fontSize: 9, color: '#CCCCCC', alignment: isArabic ? 'right' : 'left', marginTop: 2 },
            ],
            width: '*',
          },
          {
            stack: [
              { text: 'Rasmalak AI', fontSize: 11, bold: true, color: WHITE, alignment: isArabic ? 'left' : 'right', font: 'Roboto' },
              { text: generatedDateStr, fontSize: 7, color: '#CCCCCC', alignment: isArabic ? 'left' : 'right', marginTop: 2 },
            ],
            width: 'auto',
          },
        ],
      },
    ],
    marginBottom: 15,
  };

  // Input + Summary side by side
  const leftTable = {
    width: '50%',
    stack: [
      { text: isArabic ? labels.loanSummary : labels.inputParameters, fontSize: 11, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      {
        table: {
          headerRows: 0,
          widths: ['50%', '50%'],
          body: isArabic ? summaryTableBody : inputTableBody,
        },
        layout: thinGridLayout,
      },
    ],
  };

  const rightTable = {
    width: '50%',
    stack: [
      { text: isArabic ? labels.inputParameters : labels.loanSummary, fontSize: 11, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      {
        table: {
          headerRows: 0,
          widths: ['50%', '50%'],
          body: isArabic ? inputTableBody : summaryTableBody,
        },
        layout: thinGridLayout,
      },
    ],
  };

  // ===== DOCUMENT DEFINITION =====
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const docDefinition: any = {
    pageOrientation: 'landscape',
    pageSize: 'A4',
    pageMargins: [15, 15, 15, 25],

    defaultStyle: {
      font: fontFamily,
      fontSize: 8,
    },

    // Background: draw navy bar + emerald line on first page
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    background: (currentPage: number): any[] => {
      if (currentPage === 1) {
        return [
          { canvas: [{ type: 'rect', x: 0, y: 0, w: 842, h: 32, color: NAVY }] },
          { canvas: [{ type: 'rect', x: 0, y: 32, w: 842, h: 2, color: EMERALD }] },
        ];
      }
      return [];
    },

    content: [
      // Header block
      headerContent,

      // Side-by-side summary tables
      {
        columns: [leftTable, { width: 15, text: '' }, rightTable],
        marginBottom: 15,
      },

      // Amortization Schedule title
      { text: labels.amortizationSchedule, fontSize: 12, bold: true, color: NAVY, alignment: align, marginBottom: 4 },

      // Amortization table
      {
        table: {
          headerRows: 1,
          widths: Array(10).fill('*'),
          body: [amortHeaderRow, ...amortBody],
        },
        layout: amortGridLayout,
        fontSize: 6.5,
      },
    ],

    // Footer with page numbers
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    footer: (currentPage: number, pageCount: number): any => {
      const pageNum = isArabic ? toArabicNumerals(String(currentPage)) : String(currentPage);
      const totalPages = isArabic ? toArabicNumerals(String(pageCount)) : String(pageCount);
      const pageText = `${labels.page} ${pageNum} ${labels.of} ${totalPages}`;

      return {
        columns: [
          {
            text: labels.generatedBy,
            alignment: isArabic ? 'right' : 'left',
            fontSize: 7,
            color: '#808080',
            margin: isArabic ? [0, 5, 15, 0] : [15, 5, 0, 0],
            font: fontFamily,
          },
          {
            text: pageText,
            alignment: isArabic ? 'left' : 'right',
            fontSize: 7,
            color: '#808080',
            margin: isArabic ? [15, 5, 0, 0] : [0, 5, 15, 0],
            font: fontFamily,
          },
        ],
      };
    },
  };

  // ===== GENERATE & DOWNLOAD PDF =====
  const fileName = isArabic
    ? 'تقرير_سداد_القرض_السكني.pdf'
    : 'Mortgage_Payoff_Report.pdf';

  pdfMake.createPdf(docDefinition).download(fileName);
}
