/**
 * Mortgage Payoff PDF Report Generator
 * 
 * Generates a professional PDF report with loan summary and amortization schedule.
 * Supports both English (LTR) and Arabic (RTL) layouts.
 * 
 * Arabic support uses the Amiri font with text reshaping for proper rendering.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { MortgagePayoffInput, MortgagePayoffResult } from './mortgagePayoffCalculator';
import {
  processArabicText,
  formatNumberArabic,
  formatDateArabic,
  toArabicNumerals,
  registerArabicFont,
} from './arabicPdfHelper';

interface ReportLabels {
  title: string;
  subtitle: string;
  loanSummary: string;
  amortizationSchedule: string;
  loanAmount: string;
  interestRate: string;
  loanTerm: string;
  paymentsPerYear: string;
  startDate: string;
  extraPayment: string;
  lenderName: string;
  scheduledPayment: string;
  scheduledPayments: string;
  actualPayments: string;
  yearsSaved: string;
  totalEarlyPayments: string;
  totalInterest: string;
  totalPaid: string;
  pmtNo: string;
  paymentDate: string;
  beginningBalance: string;
  scheduledPmt: string;
  extraPmt: string;
  totalPayment: string;
  principal: string;
  interest: string;
  endingBalance: string;
  cumulativeInterest: string;
  generatedBy: string;
  generatedOn: string;
  page: string;
  of: string;
  years: string;
  inputParameters: string;
  currency: string;
}

const EN_LABELS: ReportLabels = {
  title: 'Mortgage Amortization Schedule',
  subtitle: 'Mortgage Payoff Report',
  loanSummary: 'Loan Summary',
  amortizationSchedule: 'Amortization Schedule',
  loanAmount: 'Loan Amount',
  interestRate: 'Interest Rate',
  loanTerm: 'Loan Term',
  paymentsPerYear: 'Payments Per Year',
  startDate: 'Repayment Start Date',
  extraPayment: 'Extra Monthly Payment',
  lenderName: 'Lender Name',
  scheduledPayment: 'Scheduled Payment',
  scheduledPayments: 'Scheduled Number of Payments',
  actualPayments: 'Actual Number of Payments',
  yearsSaved: 'Years Saved Off Original Loan Term',
  totalEarlyPayments: 'Total Early Payments',
  totalInterest: 'Total Interest',
  totalPaid: 'Total Amount Paid',
  pmtNo: 'PMT No',
  paymentDate: 'Payment Date',
  beginningBalance: 'Beginning Balance',
  scheduledPmt: 'Scheduled Payment',
  extraPmt: 'Extra Payment',
  totalPayment: 'Total Payment',
  principal: 'Principal',
  interest: 'Interest',
  endingBalance: 'Ending Balance',
  cumulativeInterest: 'Cumulative Interest',
  generatedBy: 'Generated by Rasmalak AI',
  generatedOn: 'Generated on',
  page: 'Page',
  of: 'of',
  years: 'years',
  inputParameters: 'Input Parameters',
  currency: '',
};

const AR_LABELS: ReportLabels = {
  title: 'جدول سداد القرض السكني',
  subtitle: 'تقرير سداد القرض',
  loanSummary: 'مختصر تفاصيل القرض',
  amortizationSchedule: 'جدول الأقساط',
  loanAmount: 'قيمة القرض',
  interestRate: 'نسبة الفائدة السنوية',
  loanTerm: 'مدة القرض',
  paymentsPerYear: 'عدد الدفعات في السنة',
  startDate: 'تاريخ أول دفعة سداد',
  extraPayment: 'الدفعة الإضافية',
  lenderName: 'اسم البنك المقرض',
  scheduledPayment: 'الدفعة الشهرية',
  scheduledPayments: 'عدد الدفعات الأساسية',
  actualPayments: 'عدد الدفعات الفعلي',
  yearsSaved: 'السنوات المختصرة',
  totalEarlyPayments: 'مجموع الدفعات الإضافية',
  totalInterest: 'الفائدة المدفوعة',
  totalPaid: 'إجمالي المبلغ المدفوع',
  pmtNo: 'رقم الدفعة',
  paymentDate: 'تاريخ الدفعة',
  beginningBalance: 'الرصيد الافتتاحي',
  scheduledPmt: 'الدفعة الشهرية',
  extraPmt: 'الدفعة الإضافية',
  totalPayment: 'مجموع الدفعة',
  principal: 'المبلغ الأصلي',
  interest: 'الفائدة',
  endingBalance: 'الرصيد الختامي',
  cumulativeInterest: 'الفائدة التراكمية',
  generatedBy: 'تم إنشاؤه بواسطة رسملك',
  generatedOn: 'تاريخ الإنشاء',
  page: 'صفحة',
  of: 'من',
  years: 'سنة',
  inputParameters: 'بيانات المدخلات',
  currency: '',
};

// ===== FORMATTERS =====

function formatNumber(value: number, decimals: number = 2): string {
  return value.toLocaleString('en-US', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
}

function formatDate(date: Date): string {
  const yyyy = date.getFullYear().toString();
  const mm = (date.getMonth() + 1).toString().padStart(2, '0');
  const dd = date.getDate().toString().padStart(2, '0');
  return `${yyyy}/${mm}/${dd}`;
}

// ===== ARABIC TEXT WRAPPER =====
// Wraps text processing for Arabic: reshapes + converts numerals

function arText(text: string, isArabic: boolean): string {
  if (!isArabic) return text;
  return processArabicText(text);
}

function arNum(value: number, isArabic: boolean, decimals: number = 2): string {
  if (!isArabic) return formatNumber(value, decimals);
  return formatNumberArabic(value, decimals);
}

function arDate(date: Date, isArabic: boolean): string {
  if (!isArabic) return formatDate(date);
  return formatDateArabic(date);
}

function arCurrencyValue(value: number, currencySymbol: string, isArabic: boolean): string {
  if (!isArabic) {
    return `${currencySymbol} ${formatNumber(value)}`;
  }
  // For Arabic: number in Arabic-Indic + currency symbol
  // Process currency symbol through Arabic reshaper if it contains Arabic chars
  const numStr = formatNumberArabic(value);
  const processedCurrency = processArabicText(currencySymbol);
  return `${processedCurrency} ${numStr}`;
}

// ===== MAIN PDF GENERATOR =====

export async function generateMortgagePayoffPDF(
  input: MortgagePayoffInput,
  result: MortgagePayoffResult,
  locale: string = 'en',
  currencySymbol: string = '$',
): Promise<void> {
  const isArabic = locale === 'ar';
  const labels = isArabic ? AR_LABELS : EN_LABELS;
  const fontFamily = isArabic ? 'Amiri' : 'helvetica';

  // Create PDF (landscape for the wide table)
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  // Load and register Arabic font if needed
  if (isArabic) {
    await registerArabicFont(doc);
  }

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  // ===== HEADER =====
  // Brand bar
  doc.setFillColor(10, 25, 47); // Navy
  doc.rect(0, 0, pageWidth, 28, 'F');

  // Emerald accent line
  doc.setFillColor(16, 185, 129); // Emerald
  doc.rect(0, 28, pageWidth, 2, 'F');

  // Title text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont(fontFamily, 'bold');
  const titleX = isArabic ? pageWidth - margin : margin;
  doc.text(arText(labels.title, isArabic), titleX, 14, { align: isArabic ? 'right' : 'left' });

  doc.setFontSize(10);
  doc.setFont(fontFamily, 'normal');
  doc.text(arText(labels.subtitle, isArabic), titleX, 22, { align: isArabic ? 'right' : 'left' });

  // Rasmalak branding on opposite side
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold'); // Brand name always in Latin font
  const brandX = isArabic ? margin : pageWidth - margin;
  doc.text('Rasmalak AI', brandX, 14, { align: isArabic ? 'left' : 'right' });
  doc.setFontSize(8);
  doc.setFont(fontFamily, 'normal');
  const dateNow = new Date();
  const dateStr = isArabic
    ? `${arText(labels.generatedOn, true)}: ${formatDateArabic(dateNow)}`
    : `${labels.generatedOn}: ${formatDate(dateNow)}`;
  doc.text(dateStr, brandX, 22, { align: isArabic ? 'left' : 'right' });

  let currentY = 38;

  // ===== INPUT PARAMETERS SECTION =====
  doc.setTextColor(10, 25, 47);
  doc.setFontSize(13);
  doc.setFont(fontFamily, 'bold');
  doc.text(arText(labels.inputParameters, isArabic), isArabic ? pageWidth - margin : margin, currentY, {
    align: isArabic ? 'right' : 'left',
  });
  currentY += 3;

  const yearsLabel = arText(labels.years, isArabic);

  const inputData = [
    [arText(labels.loanAmount, isArabic), arCurrencyValue(input.loanAmount, currencySymbol, isArabic)],
    [arText(labels.interestRate, isArabic), isArabic ? `%${toArabicNumerals(String(input.annualInterestRate))}` : `${input.annualInterestRate}%`],
    [arText(labels.loanTerm, isArabic), `${arNum(input.loanTermYears, isArabic, 0)} ${yearsLabel}`],
    [arText(labels.paymentsPerYear, isArabic), arNum(input.paymentsPerYear, isArabic, 0)],
    [arText(labels.startDate, isArabic), arDate(new Date(input.startDate), isArabic)],
    [arText(labels.extraPayment, isArabic), arCurrencyValue(input.extraPayment, currencySymbol, isArabic)],
    [arText(labels.lenderName, isArabic), input.lenderName || '-'], // Keep bank name as entered
  ];

  // ===== LOAN SUMMARY SECTION =====
  const summaryData = [
    [arText(labels.scheduledPayment, isArabic), arCurrencyValue(result.summary.scheduledPayment, currencySymbol, isArabic)],
    [arText(labels.scheduledPayments, isArabic), arNum(result.summary.scheduledNumberOfPayments, isArabic, 0)],
    [arText(labels.actualPayments, isArabic), arNum(result.summary.actualNumberOfPayments, isArabic, 0)],
    [arText(labels.yearsSaved, isArabic), `${arNum(result.summary.yearsSaved, isArabic)} ${yearsLabel}`],
    [arText(labels.totalEarlyPayments, isArabic), arCurrencyValue(result.summary.totalEarlyPayments, currencySymbol, isArabic)],
    [arText(labels.totalInterest, isArabic), arCurrencyValue(result.summary.totalInterest, currencySymbol, isArabic)],
    [arText(labels.totalPaid, isArabic), arCurrencyValue(result.summary.totalPaid, currencySymbol, isArabic)],
  ];

  // Side by side summary tables
  const halfWidth = (pageWidth - margin * 3) / 2;
  const halign = isArabic ? 'right' as const : 'left' as const;

  // Input Parameters Table
  autoTable(doc, {
    startY: currentY,
    margin: { left: isArabic ? pageWidth / 2 + margin / 2 : margin, right: isArabic ? margin : pageWidth / 2 + margin / 2 },
    head: [[arText(labels.inputParameters, isArabic), '']],
    body: inputData,
    theme: 'grid',
    styles: {
      font: fontFamily,
    },
    headStyles: {
      fillColor: [16, 185, 129],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
      halign,
    },
    bodyStyles: {
      fontSize: 8,
      halign,
      cellPadding: 2,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: halfWidth * 0.55 },
      1: { cellWidth: halfWidth * 0.45 },
    },
    alternateRowStyles: {
      fillColor: [245, 250, 248],
    },
  });

  // Loan Summary Table
  autoTable(doc, {
    startY: currentY,
    margin: { left: isArabic ? margin : pageWidth / 2 + margin / 2, right: isArabic ? pageWidth / 2 + margin / 2 : margin },
    head: [[arText(labels.loanSummary, isArabic), '']],
    body: summaryData,
    theme: 'grid',
    styles: {
      font: fontFamily,
    },
    headStyles: {
      fillColor: [10, 25, 47],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
      halign,
    },
    bodyStyles: {
      fontSize: 8,
      halign,
      cellPadding: 2,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: halfWidth * 0.55 },
      1: { cellWidth: halfWidth * 0.45 },
    },
    alternateRowStyles: {
      fillColor: [240, 244, 255],
    },
  });

  // Get the Y position after both tables
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const finalY = (doc as any).lastAutoTable?.finalY || currentY + 60;
  currentY = finalY + 10;

  // ===== AMORTIZATION SCHEDULE =====
  doc.setFontSize(13);
  doc.setFont(fontFamily, 'bold');
  doc.setTextColor(10, 25, 47);
  doc.text(arText(labels.amortizationSchedule, isArabic), isArabic ? pageWidth - margin : margin, currentY, {
    align: isArabic ? 'right' : 'left',
  });
  currentY += 3;

  // Table headers
  const tableHeaders = [
    arText(labels.pmtNo, isArabic),
    arText(labels.paymentDate, isArabic),
    arText(labels.beginningBalance, isArabic),
    arText(labels.scheduledPmt, isArabic),
    arText(labels.extraPmt, isArabic),
    arText(labels.totalPayment, isArabic),
    arText(labels.principal, isArabic),
    arText(labels.interest, isArabic),
    arText(labels.endingBalance, isArabic),
    arText(labels.cumulativeInterest, isArabic),
  ];

  // If RTL, reverse the columns order
  const headers = isArabic ? [...tableHeaders].reverse() : tableHeaders;

  // Table body
  const tableBody = result.schedule.map((row) => {
    const rowData = [
      arNum(row.paymentNumber, isArabic, 0),
      arDate(row.paymentDate, isArabic),
      arCurrencyValue(row.beginningBalance, currencySymbol, isArabic),
      arCurrencyValue(row.scheduledPayment, currencySymbol, isArabic),
      arCurrencyValue(row.extraPayment, currencySymbol, isArabic),
      arCurrencyValue(row.totalPayment, currencySymbol, isArabic),
      arCurrencyValue(row.principal, currencySymbol, isArabic),
      arCurrencyValue(row.interest, currencySymbol, isArabic),
      arCurrencyValue(row.endingBalance, currencySymbol, isArabic),
      arCurrencyValue(row.cumulativeInterest, currencySymbol, isArabic),
    ];
    return isArabic ? [...rowData].reverse() : rowData;
  });

  autoTable(doc, {
    startY: currentY,
    margin: { left: margin, right: margin },
    head: [headers],
    body: tableBody,
    theme: 'grid',
    styles: {
      font: fontFamily,
      lineColor: [200, 200, 200],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: [10, 25, 47],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7,
      halign: 'center',
      cellPadding: 1.5,
    },
    bodyStyles: {
      fontSize: 6.5,
      halign: 'center',
      cellPadding: 1.2,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    // Add page footer
    didDrawPage: (data) => {
      // Footer with page numbers
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(7);
      doc.setTextColor(128, 128, 128);
      doc.setFont(fontFamily, 'normal');

      // Footer line
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

      // Left: branding
      const footerBrand = isArabic
        ? arText(labels.generatedBy, true)
        : labels.generatedBy;
      doc.text(footerBrand, isArabic ? pageWidth - margin : margin, pageHeight - 7, {
        align: isArabic ? 'right' : 'left',
      });

      // Right: page number
      const pageLabel = arText(labels.page, isArabic);
      const ofLabel = arText(labels.of, isArabic);
      const pageNum = isArabic ? toArabicNumerals(String(data.pageNumber)) : String(data.pageNumber);
      const totalPages = isArabic ? toArabicNumerals(String(pageCount)) : String(pageCount);
      const pageText = `${pageLabel} ${pageNum} ${ofLabel} ${totalPages}`;
      doc.text(pageText, isArabic ? margin : pageWidth - margin, pageHeight - 7, {
        align: isArabic ? 'left' : 'right',
      });
    },
  });

  // Save the PDF
  const fileName = isArabic
    ? 'تقرير_سداد_القرض_السكني.pdf'
    : 'Mortgage_Payoff_Report.pdf';

  doc.save(fileName);
}
