/**
 * Simple Loan PDF Report Generator
 */

import type { SimpleLoanInput, SimpleLoanResult } from './simpleLoanCalculator';
import {
  initPdfMake,
  buildHeaderContent,
  buildBackground,
  buildFooter,
  fmtCurrency,
  fmtNum,
  fmtDate,
  lbl,
  rtl,
  formatDateArabic,
  formatDate,
  thinGridLayout,
  amortGridLayout,
  NAVY,
  WHITE,
  LIGHT_GRAY,
  ALT_ROW_GREEN,
  ALT_ROW_BLUE,
} from './pdfReportBase';

// ===== LABELS =====

interface Labels {
  title: string; subtitle: string; inputParameters: string; loanSummary: string;
  loanAmount: string; interestRate: string; loanPeriod: string; startDate: string;
  monthlyPayment: string; numberOfPayments: string; totalInterest: string; totalCost: string;
  amortizationSchedule: string;
  pmtNo: string; paymentDate: string; beginningBalance: string; payment: string;
  principal: string; interest: string; endingBalance: string;
  generatedBy: string; generatedOn: string; page: string; of: string; years: string;
}

const EN: Labels = {
  title: 'Loan Amortization Schedule', subtitle: 'Simple Loan Report',
  inputParameters: 'Input Parameters', loanSummary: 'Loan Summary',
  loanAmount: 'Loan Amount', interestRate: 'Interest Rate', loanPeriod: 'Loan Period',
  startDate: 'Start Date',
  monthlyPayment: 'Monthly Payment', numberOfPayments: 'Number of Payments',
  totalInterest: 'Total Interest', totalCost: 'Total Cost of Loan',
  amortizationSchedule: 'Amortization Schedule',
  pmtNo: 'No.', paymentDate: 'Payment Date', beginningBalance: 'Beginning Balance',
  payment: 'Payment', principal: 'Principal', interest: 'Interest', endingBalance: 'Ending Balance',
  generatedBy: 'Generated by Rasmalak AI', generatedOn: 'Generated on',
  page: 'Page', of: 'of', years: 'years',
};

const AR: Labels = {
  title: 'جدول سداد القرض', subtitle: 'تقرير القرض البسيط',
  inputParameters: 'بيانات المدخلات', loanSummary: 'ملخص القرض',
  loanAmount: 'مبلغ القرض', interestRate: 'نسبة الفائدة السنوية', loanPeriod: 'مدة القرض',
  startDate: 'تاريخ بداية القرض',
  monthlyPayment: 'الدفعة الشهرية', numberOfPayments: 'عدد الدفعات',
  totalInterest: 'إجمالي الفائدة', totalCost: 'التكلفة الإجمالية للقرض',
  amortizationSchedule: 'جدول الأقساط',
  pmtNo: 'رقم', paymentDate: 'تاريخ الدفعة', beginningBalance: 'الرصيد الافتتاحي',
  payment: 'الدفعة', principal: 'المبلغ الأصلي', interest: 'الفائدة', endingBalance: 'الرصيد الختامي',
  generatedBy: 'تم إنشاؤه بواسطة رسملك', generatedOn: 'تاريخ الإنشاء',
  page: 'صفحة', of: 'من', years: 'سنة',
};

// ===== MAIN =====

export async function generateSimpleLoanPDF(
  input: SimpleLoanInput,
  result: SimpleLoanResult,
  locale: string = 'en',
  currencySymbol: string = '$',
): Promise<void> {
  const isArabic = locale === 'ar';
  const labels = isArabic ? AR : EN;
  const align = isArabic ? 'right' as const : 'left' as const;
  const fontFamily = isArabic ? 'Amiri' : 'Roboto';

  const pdfMake = await initPdfMake(isArabic);

  const now = new Date();
  const generatedDateStr = isArabic
    ? rtl(`${labels.generatedOn}: ${formatDateArabic(now)}`)
    : `${labels.generatedOn}: ${formatDate(now)}`;

  // Input table
  const inputRows = [
    [lbl(labels.loanAmount, isArabic), fmtCurrency(input.loanAmount, currencySymbol, isArabic)],
    [lbl(labels.interestRate, isArabic), isArabic ? rtl(`${fmtNum(input.annualInterestRate, isArabic)}%`) : `${input.annualInterestRate}%`],
    [lbl(labels.loanPeriod, isArabic), isArabic ? rtl(`${fmtNum(input.loanPeriodYears, isArabic, 0)} ${labels.years}`) : `${input.loanPeriodYears} ${labels.years}`],
    [lbl(labels.startDate, isArabic), fmtDate(new Date(input.startDate), isArabic)],
  ];

  // Summary table
  const summaryRows = [
    [lbl(labels.monthlyPayment, isArabic), fmtCurrency(result.summary.monthlyPayment, currencySymbol, isArabic)],
    [lbl(labels.numberOfPayments, isArabic), fmtNum(result.summary.numberOfPayments, isArabic, 0)],
    [lbl(labels.totalInterest, isArabic), fmtCurrency(result.summary.totalInterest, currencySymbol, isArabic)],
    [lbl(labels.totalCost, isArabic), fmtCurrency(result.summary.totalCost, currencySymbol, isArabic)],
  ];

  const buildTable = (rows: string[][], altColor: string) =>
    rows.map((row, idx) => {
      const fill = idx % 2 === 1 ? altColor : undefined;
      const cells = [
        { text: row[0], bold: true, alignment: align, fillColor: fill },
        { text: row[1], alignment: align, fillColor: fill },
      ];
      return isArabic ? cells.reverse() : cells;
    });

  // Amortization headers
  const amortHeaders = [
    labels.pmtNo, labels.paymentDate, labels.beginningBalance,
    labels.payment, labels.principal, labels.interest, labels.endingBalance,
  ].map(h => lbl(h, isArabic));

  const amortHeaderRow = (isArabic ? [...amortHeaders].reverse() : amortHeaders).map(h => ({
    text: h, bold: true, fontSize: 7, color: WHITE, fillColor: NAVY, alignment: 'center' as const,
  }));

  const amortBody = result.schedule.map((row, idx) => {
    const fillColor = idx % 2 === 1 ? LIGHT_GRAY : undefined;
    const cells = [
      { text: fmtNum(row.paymentNumber, isArabic, 0), alignment: 'center' as const, fillColor },
      { text: fmtDate(row.paymentDate, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.beginningBalance, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.payment, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.principal, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.interest, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
      { text: fmtCurrency(row.endingBalance, currencySymbol, isArabic), alignment: 'center' as const, fillColor },
    ];
    return isArabic ? cells.reverse() : cells;
  });

  const leftTable = {
    width: '50%',
    stack: [
      { text: lbl(isArabic ? labels.loanSummary : labels.inputParameters, isArabic), fontSize: 11, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      { table: { headerRows: 0, widths: ['50%', '50%'], body: isArabic ? buildTable(summaryRows, ALT_ROW_BLUE) : buildTable(inputRows, ALT_ROW_GREEN) }, layout: thinGridLayout },
    ],
  };

  const rightTable = {
    width: '50%',
    stack: [
      { text: lbl(isArabic ? labels.inputParameters : labels.loanSummary, isArabic), fontSize: 11, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      { table: { headerRows: 0, widths: ['50%', '50%'], body: isArabic ? buildTable(inputRows, ALT_ROW_GREEN) : buildTable(summaryRows, ALT_ROW_BLUE) }, layout: thinGridLayout },
    ],
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const docDefinition: any = {
    pageOrientation: 'landscape',
    pageSize: 'A4',
    pageMargins: [15, 15, 15, 25],
    defaultStyle: { font: fontFamily, fontSize: 8 },
    background: buildBackground,
    content: [
      buildHeaderContent(labels.title, labels.subtitle, generatedDateStr, isArabic, fontFamily),
      { columns: [leftTable, { width: 15, text: '' }, rightTable], marginBottom: 15 },
      { text: lbl(labels.amortizationSchedule, isArabic), fontSize: 12, bold: true, color: NAVY, alignment: align, marginBottom: 4 },
      { table: { headerRows: 1, widths: Array(7).fill('*'), body: [amortHeaderRow, ...amortBody] }, layout: amortGridLayout, fontSize: 6.5 },
    ],
    footer: buildFooter(labels.generatedBy, labels.page, labels.of, isArabic, fontFamily),
  };

  const fileName = isArabic ? 'تقرير_القرض_البسيط.pdf' : 'Simple_Loan_Report.pdf';
  pdfMake.createPdf(docDefinition).download(fileName);
}



